# files to compile
OBJS = $(file).cpp ../XM_SDL.cpp

# compiler
CC = g++

# compiler flags
#COMPILER_FLAGS =

# libraries to link
LINKER_FLAGS = -lSDL2

# executable name
OBJ_NAME = $(file).exe

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)



